language: bash
sudo: required
os: linux

install:
  - sudo curl -Lso /usr/bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.5/shellcheck
  - sudo chmod +x /usr/bin/shellcheck

script:
  - cmake . && sudo make install
  - shellcheck /usr/local/bin/dune_setup* /usr/local/share/dune/dune_*

notifications:
  email: false
