language: bash
sudo: required
os: linux

install:
  - sudo curl -Lso /usr/bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.5/shellcheck
  - sudo chmod +x /usr/bin/shellcheck

script:
  - for i in utils.bash setup setup_module setup_only ; do shellcheck dune_${i} ; done
  - cmake . && sudo make install

notifications:
  email: false
