language: bash
sudo: required
os: linux

install:
  - sudo curl -Lso /usr/bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.5/shellcheck
  - sudo chmod +x /usr/bin/shellcheck

script:
  - for i in setup setup_module setup_only ; do shellcheck /usr/local/bin/dune_${i} ; done
  - for i in utils.bash ; do shellcheck /usr/local/share/dune/dune_${i} ; done
  - cmake . && sudo make install

notifications:
  email: false
